resolver: lts-20.20

packages:
  - .

extra-deps:
  - Cabal-3.6.3.0
  - Cabal-syntax-3.10.1.0
  - aeson-2.1.2.1
  - cabal-install-parsers-0.6.1
  - chs-cabal-0.1.1.1
  - chs-deps-0.1.0.0
  - generic-arbitrary-0.2.2@sha256:202ffbf2032672a51318f2e80d7e75b72f8950e690346b4314f38bc7e39215f7,1189
  - generically-0.1.1
  - haskus-utils-data-1.4@sha256:bfa94363b94b14779edd6834fbd59dbb847c3d7b8f48e3844f456ffdc077da4a,1466
  - haskus-utils-types-1.5.1@sha256:991c472f4e751e2f0d7aab6ad4220ef151d6160876dcf0511bbf876bbd432020,1298
  - haskus-utils-variant-3.2.1
  - libarchive-3.0.3.2
  - libyaml-streamly-0.2.1
  - lzma-static-5.2.5.5
  - os-release-1.0.2.1
  - parsec-3.1.15.0
  - streamly-0.8.2@sha256:ec521b7c1c4db068501c35804af77f40b7d34232f5e29d9b99e722229040eb80,23500
  - strict-base-0.4.0.0
  - text-2.0.2
  - yaml-streamly-0.12.2

flags:
  http-io-streams:
    brotli: false

  libarchive:
    system-libarchive: true

  regex-posix:
    _regex-posix-clib: true

  aeson-pretty:
    lib-only: true

  cabal-plan:
    exe: false

  streamly:
    use-unliftio: true

ghc-options:
  "$locals": -O2
  streamly: -O2 -fspec-constr-recursive=16 -fmax-worker-args=16
  ghcup: -O2 -fspec-constr-recursive=16 -fmax-worker-args=16

build:
  test: true
  test-arguments:
    no-run-tests: true
  bench: true
  benchmark-opts:
    no-run-benchmarks: true
