resolver: lts-24.37

packages:
  - .


extra-deps:
  - libarchive-3.0.4.2
  - xz-5.6.3
  - xz-clib-5.6.3
  - file-uri-0.1.0.0@sha256:82b67416a75ed01ee1bb46a4662d7195cfc86e8f1342df659d0cc9ca1e18abe2,1857
  - os-release-1.0.2.1@sha256:2c3e8f7a9a0e17d5042d14d2036d52b42c8d5606e8d004697af462a95c87a9e2,2718
  - strict-base-0.4.0.0@sha256:2ff4e43cb95eedf2995558d7fc34d19362846413dd39e6aa6a5b3ea8228fef9f,1248
  - variant-1.0.1@sha256:97364d20e13ad92e02bb45e78876087ffb3b2979f39a82cadb10df1b3a920268,2182
  - zip-2.1.0@sha256:e1fcdab8f7b01d8a78ef4a8c6f584fe4d7e42e89de870f310ab293b6e0ffda07,4026
allow-newer: true

allow-newer-deps:
  - Cabal
  - Cabal-syntax
  - process
  - terminal-size

flags:
  http-io-streams:
    brotli: false

  libarchive:
    system-libarchive: false

  xz:
    system-xz: false

  regex-posix:
    _regex-posix-clib: true

  aeson-pretty:
    lib-only: true

  cabal-plan:
    exe: false

  ghcup:
    tar: true

  dhall:
    cross: false
    with-http: false
    network-tests: false

ghc-options:
  "$locals": -O2
  ghcup: -O2 -fspec-constr-recursive=16 -fmax-worker-args=16

build:
  test: true
  test-arguments:
    no-run-tests: true
  bench: true
  benchmark-opts:
    no-run-benchmarks: true
