when:
  - platform: freebsd/amd64
  - event: push
  - event: manual

skip_clone: true

steps:
 - name: build
   image: win10
   commands:
     - cd
     - Set-Content -Path ".\hello.txt" -Value "hello"
   backend_options:
     libvirt:
       ephemeral: true
       shared_disk:
         uuid: BHYVE-EACC-BD89-8B7D
         disk_config: |
           <disk type='file' device='disk'>
             <source file='/var/lib/libvirt/images/win10-shared.img'/>
             <target dev='sdb' bus='sata'/>
             <address type='drive' controller='0' bus='0' target='0' unit='1'/>
           </disk>
       ssh_config:
         username: maerwald
         password: anevasti
         timeout: 2m
         hostname: win10
# - name: build
#   image: vm1
#   commands:
#     - mount
#     - ls -lah /woodpecker
#     - pwd
#     - ls -lah
#     - echo "This is the build step"
#   backend_options:
#     libvirt:
#       ephemeral: true
#       shared_disk:
#         uuid: bd5ea041-e765-4d3a-9cda-083e4e52b187
#         disk_image: /var/lib/libvirt/images/shared.qcow2
#       ssh_config:
#         username: root
#         password: root
#         timeout: 1m
#         interface: eth0
