when:
  - platform: freebsd/amd64
  - event: push
  - event: manual

skip_clone: true

steps:
  - name: build
    image: vm1
    commands:
      - echo "This is the build step"
      - ls -lah
    backend_options:
      ssh_config:
        username: root
        password: root
